language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t djsmallman/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true djsmallman/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-997493607229"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

